defmodule Pencil.Discord.Util do
  @embed_color Application.compile_env!(:pencil_discord, [:bot, :embed_color])
  @embed_color_error 0xA80D29
  alias Nostrum.Struct.Embed

  def begin_embed() do
    begin_embed(@embed_color)
  end

  def begin_embed(:error) do
    begin_embed(@embed_color_error)
  end

  def begin_embed(color) when is_integer(color) do
    ts = DateTime.utc_now()
    bot_name = Nostrum.Cache.Me.get().username
    footer = "This embed generated by #{bot_name} at #{DateTime.to_string(ts)}"

    %Embed{
      color: color,
      footer: %Embed.Footer{
        text: footer
      },
      timestamp: ts
    }
  end
end
